name: PR Checks - advogaAI-server

on:
  pull_request:
    paths:
      - "advogaAI-server/**"
    branches:
      - main
      - stg
      - dev

jobs:
  lint-test-build:
    name: Lint, Test and Build (advogaAI-server)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: advogaAI-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: advogaAI-server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build
