name: Pull-to-server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev
            branch: dev
            base_path: "advogaai/advogaai_dev"
          - name: main
            branch: main
            base_path: "advogaai/advogaai_prod"

    steps:
      - name: Checkout do código
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        uses: actions/checkout@v3

      - name: Copiar advogaAI-server para o server
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          # AQUI: source aponta para a pasta interna "advogaAI-server/advogaAI-server"
          source: "advogaAI-server/."
          target: "/home/${{ secrets.USER }}/${{ matrix.base_path }}"

      - name: Executar comandos remotos no server (build/seed etc.)
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            echo "=== BACKEND (advogaAI-server) [${{ matrix.name }}] ==="
            cd "/home/${{ secrets.USER }}/${{ matrix.base_path }}/advogaAI-server"
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npm run gen:keys
            npm run build
            echo "Deploy concluído em $(date)"
          EOF
        shell: bash
